---
apiVersion: v1
kind: Pod
spec:
  #securityContext:
  #  runAsUser: 1000
  containers:
  - name: maven
    image: maven:3.8.6-openjdk-11-slim
    env:
      - name: HTTP_PROXY
        value: null
      - name: HTTPS_PROXY
        value: null
    command: ['cat']
    tty: true